baseurl = "https://aochagavia.github.io/"
author = "Adolfo Ochagavía"
title = "aochagavia's blog"
languageCode = "en-us"
paginate = 5
theme = "cocoa"
enableRobotsTXT = true
PygmentsCodeFences = true

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[Params]
author = "Aochagavia's Blog"
dateform = "Jan 02, 2006"
dateformfull = "January 02, 2006"
description = "Just another programming blog"
github = "//github.com/aochagavia"
linkedin = "//www.linkedin.com/in/adolfoochagavia/"
